apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic-container
        image: ibuchh/petclinic-spinnaker-jenkins
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 8080  # Expose a different port on the service, if needed
      targetPort: 8082
  type: NodePort  # Change this line to NodePort

